### ISSUE TITLE
Could you please clarify the license for the emoji assets?

### ISSUE THREAD

**Issue by adeopura4** [terranisu/angular-emoji-picker#25]
Could you please clarify where you got the emoji assets from and their associated licensing information? Thank you.

**Comment by terranisu** [comment]
Hmm, I wish I could, but it's hard to say where exactly I've got them from. I just googled somewhere on the Internet many years ago. Why? Do they belong to you?

**Comment by adeopura4** [comment]
Thank you for your response. They do not belong to me! I wanted to use your library for a project, but I can use only if the license allows me to use the assets (emojis). I think this might also be helpful to others who might want to use your library. Anyway, thank you for creating this nice library.
