### ISSUE TITLE
Allow picker to output unicode instead of text

### ISSUE THREAD

**Issue by aendrew** [terranisu/angular-emoji-picker#8]
Hi!

I've written a validator for a project of mine that ensures the only text in a box is emoji. See [aendrew/angular-emoji-directive](https://github.com/aendrew/angular-emoji-directive). 

I was wondering — is there a way to make the text box output the unicode character instead of the text approximation of that? I enjoy living dangerously and am wanting to save a whole bunch of astral code page unicode characters to my database. :smile:

**Comment by terranisu** [comment]
Hi, @aendrew

I'm not quite sure that understood your question correctly. Are you just wondering how to do it or do you want that feature would be implemented in the picker?

**Comment by aendrew** [comment]
I'm wondering whether there's an option for it or not, and if there's not, suggesting it as a feature request. Mobile users quite frequently use the unicode emoji because they have pickers built into their OS; by allowing the unicode version to be output, you can use angular-emoji-picker as a way of bridging that experience between mobile and desktop.

**Comment by terranisu** [comment]
Ok, I could try to add this feature, but I don't when exactly.

**Comment by aendrew** [comment]
If interested, I've modified my fork to allow this; see: https://github.com/aendrew/angular-emoji-picker/tree/return_unicode

It's pretty messy; could clean it up into a PR if interested!

**Comment by terranisu** [comment]
It seems great. But to merge your code into master I think I need to change whole conception of the picker =) Give me a little time to think about it.

**Comment by aendrew** [comment]
@terranisu I got bored so I rewrote my changes and did a PR. Now it outputs as unicode only if the attribute "output" is set to "unicode".

**Comment by terranisu** [comment]
I've added opportunity to output unicode

**Comment by aendrew** [comment]
@terranisu Cool! Thanks!
